services:
  rsyslog:
    image: rsyslog/rsyslog:latest
    container_name: rsyslog
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
      - ./logs:/var/log/docker
    restart: always

  logspout:
    image: gliderlabs/logspout:latest
    container_name: logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rsyslog
    command: syslog+udp://rsyslog:514
    restart: always

  logrotate:
    image: blacklabelops/logrotate
    container_name: logrotate
    volumes:
      - ./logs:/var/log/docker
      - ./logrotate.conf:/etc/logrotate.conf:ro
    environment:
      - LOGS_DIRECTORIES=/var/log/docker
      - LOGROTATE_CRONSCHEDULE=*/5 * * * *   # 每5分钟执行一次
    restart: always

  nginx:
    image: nginx:alpine
    container_name: logserver
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/usr/share/nginx/html/logs:ro
    restart: always
