services:
  mysql:
    image: mysql:8.0
    container_name: mysql8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--bind-address=0.0.0.0"
    ]
    volumes:
      - /home/jcy/mysql8/mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local