services:
  jenkins:
    # image: jenkins/jenkins:jdk21
    build: .
    container_name: jenkins
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/jcy/jenkins/data/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/local/bin/aliyun:/usr/local/bin/aliyun
      - /root/.aliyun:/root/.aliyun
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx4096m
    mem_limit: 4g